[package]
name = "client"
version = "0.1.0"
authors = ["Talasan Nicholson <talasan.nicholson@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies.stdweb]
git = "https://github.com/koute/stdweb"
