[package]
name = "client"
version = "0.1.0"
authors = ["Talasan Nicholson <talasan.nicholson@gmail.com>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
maplit = "^1"

[dependencies.stdweb]
git = "https://github.com/koute/stdweb"
