[package]
name = "nextrs_server"
version = "0.1.0"
authors = ["Talasan Nicholson <talasan.nicholson@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = { git = "https://github.com/koute/stdweb" }
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
