[package]
build = "./build.rs"
name = "nextrs_client"
version = "0.1.0"
authors = ["Talasan Nicholson <talasan.nicholson@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = { git = "https://github.com/koute/stdweb" }
