[package]
name = "server"
version = "0.1.0"
authors = ["Talasan Nicholson <talasan.nicholson@gmail.com>"]

[dependencies]
actix = "0.5"
env_logger = "0.5"
tera = "0.11"
lazy_static = "1.0"

[dependencies.actix-web]
version = "^0.6"
default-features=false

[dependencies.client]
path = "./../client"
