brace_style = "PreferSameLine
condense_wildcard_suffixes = true
fn_args_density = "Compressed"
fn_single_line = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
max_width = 89
merge_imports = true
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
tab_spaces = 2
trailing_coma = "Never"
trailing_semicolon = false
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
