[package]
name = "nextrs_server"
version = "0.1.0"
authors = ["Talasan Nicholson <talasan.nicholson@gmail.com>"]

[dependencies]
actix = "0.5"
env_logger = "0.5"

[dependencies.actix-web]
version = "^0.6"
default-features=false

#[dependency.nextrs_client]
#path = "../client/"
